---
# Default variable
vagrant_host: default-test
home_dir: /home/{{ ansible_user }}
downloads_dir: /home/{{ ansible_user }}/Downloads

# List of users that will be created on system
active_users:
  - { username: 'mataberat', groups: 'root', home: '/home/mataberat' }
  - { username: 'dzulfia', groups: 'root', home: '/home/dzulfia' }
  - { username: 'wibono', groups: 'root', home: '/home/wibono' }
  - { username: 'aris', groups: 'root', home: '/home/aris' }
  - { username: 'agung', groups: 'root', home: '/home/agung'}

deactive_users:
  - { username: 'usertest', groups: 'root', home: '/home/usertest' }

# List of firewall rules that will enabled on system
csf_tcp_in: 20,21,22,25,53,80,110,143,443,465,587,993,995 
csf_tcp_out: 20,21,22,25,53,80,110,113,443
csf_udp_in: 20,21,53
csf_udp_out: 20,21,53,113,123