---
vagrant_host: default-test
home_dir: /home/{{ ansible_user }}
downloads_dir: /home/{{ ansible_user }}/Downloads

csf_tcp_in: 20,21,22,25,53,80,110,143,443,465,587,993,995 
csf_tcp_out: 20,21,22,25,53,80,110,113,443