- name: Check if nginx already installed
  command: nginx -v
  register: nginx_installed_result
  ignore_errors: true
  changed_when: false
  tags: nginx

- name: Add ppa:nginx/stable
  apt_repository:
    repo: ppa:nginx/stable
    update_cache: yes
  tags: nginx
  when: nginx_installed_result is failed

- name: Installing nginx
  apt: name="nginx={{ nginx_version }}*"
  tags: nginx
  when: nginx_installed_result is failed

- name: Enable nginx service
  service:
    name: nginx
    enabled: true
    use: service
    state: started
  tags: nginx
  when: nginx_installed_result is failed

- name: Restart service nginx, in all cases
  service:
    name: nginx
    state: restarted
  tags: nginx

- name: Make sure nginx is running
  systemd:
    state: started
    name: nginx
  tags: nginx