- name: Vagrant for default-webserver
  hosts: vagrant-default-webserver
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: yes

  roles:
  - { role: kambing-repository }
  - { role: common }
  - { role: nginx-php-fpm }
