- name: Change repository to Kambing
  copy: src=id.sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  tags: common, bootup_config

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600
  tags: common, bootup_config
